name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
  GCLOUD_EMAIL: ${{ secrets.GCLOUD_EMAIL }}
  GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
  GCLOUD_APP_NAME: ${{ secrets.GCLOUD_APP_NAME }}
  GITHUB_SHA: ${{ github.sha }}
  GCLOUD_REGION: us-central1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    # Setup gcloud CLI
    # - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    - run: |
        echo $GCLOUD_KEY | base64 --decode > /tmp/gcloudKey.json
        gcloud auth activate-service-account $GCLOUD_EMAIL --key-file=/tmp/gcloudKey.json
    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
    # Build the Docker image
    - name: Build
      run: |
        docker build -t gcr.io/"$GCLOUD_PROJECT"/"$GCLOUD_APP_NAME":"$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push gcr.io/$GCLOUD_PROJECT/$GCLOUD_APP_NAME:$GITHUB_SHA
    - name: Deploy application on cloud run
      run: |
        gcloud beta run deploy $GCLOUD_APP_NAME --quiet \
          --image gcr.io/$GCLOUD_PROJECT/$GCLOUD_APP_NAME:$GITHUB_SHA \
          --project $GCLOUD_PROJECT --region $GCLOUD_REGION --platform managed
